{"uuid": "ae405d75-a99e-4513-8317-25022332e243", "counter": 192, "stdout": "\u001b[0;31mfatal: [localhost]: FAILED! => {\u001b[0m\r\n\u001b[0;31m    \"msg\": \"The conditional check '\\\"segment\\\" in item.type' failed. The error was: error while evaluating conditional (\\\"segment\\\" in item.type): 'dict object' has no attribute 'type'\\n\\nThe error appears to be in '/data/project/playbooks/step02.yml': line 75, column 5, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n  - name: generate config\\n    ^ here\\n\"\u001b[0m\r\n\u001b[0;31m}\u001b[0m", "start_line": 2546, "end_line": 2549, "runner_ident": "152db048-7703-4fd0-bbb5-b790c7d2f2ca", "event": "runner_on_failed", "pid": 24, "created": "2023-04-07T08:15:55.019499", "parent_uuid": "0242ac16-0009-6119-3e84-00000000000d", "event_data": {"playbook": "/data/project/playbooks/step02.yml", "playbook_uuid": "ed1811b7-1877-4985-aee4-26a424ae6251", "play": "localhost", "play_uuid": "0242ac16-0009-6119-3e84-000000000008", "play_pattern": "localhost", "task": "generate config", "task_uuid": "0242ac16-0009-6119-3e84-00000000000d", "task_action": "template", "resolved_action": "ansible.builtin.template", "task_args": "", "task_path": "/data/project/playbooks/step02.yml:75", "host": "localhost", "remote_addr": "localhost", "res": {"msg": "The conditional check '\"segment\" in item.type' failed. The error was: error while evaluating conditional (\"segment\" in item.type): 'dict object' has no attribute 'type'\n\nThe error appears to be in '/data/project/playbooks/step02.yml': line 75, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: generate config\n    ^ here\n", "_ansible_no_log": false}, "start": "2023-04-07T08:15:54.998862", "end": "2023-04-07T08:15:55.019228", "duration": 0.020366, "ignore_errors": null, "event_loop": null, "uuid": "ae405d75-a99e-4513-8317-25022332e243"}}